name: Build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0 # Need to fetch all for proper history
            -   name: Collect build info
                id: info
                run: |
                    # Get short SHA
                    SHA_SHORT=$(git rev-parse --short HEAD)
                    echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
                    
                    # Extract version from csproj
                    VERSION=$(grep -oP '(?<=<Version>)[^<]+' BepisResoniteHooks/BepisResoniteHooks.csproj)
                    echo "version=$VERSION" >> $GITHUB_OUTPUT
                    echo "Version found: $VERSION"
            -   uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: "9.0.x"
            -   name: Build
                run: |
                    dotnet build -c Release
                    dotnet pack -c Release --no-build -o ./bin/dist
                    # Copy the built DLL to dist folder
                    cp ./BepisResoniteHooks/bin/Release/BepisResoniteHooks.dll ./bin/dist/
            -   name: Upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: BepisResoniteHooks-${{ steps.info.outputs.version }}-${{ steps.info.outputs.sha_short }}
                    path: |
                        ./bin/dist/*.nupkg
                        ./bin/dist/*.dll